//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProje
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EntityProjeEntities : DbContext
    {
        public EntityProjeEntities()
            : base("name=EntityProjeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<kategori> kategori { get; set; }
        public virtual DbSet<Musteri> Musteri { get; set; }
        public virtual DbSet<Satıs> Satıs { get; set; }
        public virtual DbSet<Urun> Urun { get; set; }
    
        public virtual ObjectResult<string> MarkayıBulma()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("MarkayıBulma");
        }
    }
}
